access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://Sisari:paf16@paf16.ogqnlor.mongodb.net/Paf16?retryWrites=true&w=majority
logging:
  level:
    org.springframework.security: DEBUG
